apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: checkout
resources:
- namespace.yaml
- configmap.yaml
- serviceaccount.yaml
- service.yaml
- redis-service.yaml
- deployment.yaml
- redis.yaml