---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: carts
resources:
- namespace.yaml
- configmap.yaml
- serviceaccount.yaml
- service.yaml
- db-service.yaml
- deployment.yaml
- db.yaml