# The API key the Flows flow uses to approve or reject Spacelift runs. The
# approval policy generated by the plugin only counts reviews from this key.
resource "spacelift_api_key" "jira_approval" {
  name = "jira-approval-flow"
}

resource "spacelift_role_attachment" "jira_approval_admin" {
  api_key_id = spacelift_api_key.jira_approval.id
  role_id    = var.admin_role_id
  space_id   = "root"
}
