creation_rules:
  - kms: arn:aws:kms:us-east-1:234878555361:key/6462da8d-e99d-4bb6-98d6-1b7e8561ecc0

secrets:
  - catalog/secret.yaml
  - orders/secret.yaml
  - rabbitmq/secret.yaml
  - orders/mysql.yaml



