---
- name: Install and Configure Nginx
  hosts: all
  remote_user: ubuntu
  become: yes
  roles:
    - { role: geerlingguy.nginx }

  vars:
    nginx_vhosts:
      - listen: "80"
        server_name: '{{ inventory_hostname }}'
        root: "/usr/share/nginx/html/"
        index: "index.html"

  tasks:
    - name: Create index.html
      ansible.builtin.copy:
        dest: /usr/share/nginx/html/index.html
        content: |
          <!DOCTYPE html>
          <html>
          <head><title>Spacelift Ansible Demo</title></head>
          <body>
          <div style="text-align: center;">
            <h1>Served from {{ inventory_hostname }}</h1>
            <p>Triggered from Spacelift via run:</p>
            <p>
              <a href="https://spacelift-solutions.app.spacelift.io/stack/ansible-ec2/run/{{ lookup('ansible.builtin.env', 'TF_VAR_spacelift_run_id') }}">
                https://spacelift-solutions.app.spacelift.io/stack/ansible-ec2/run/{{ lookup('ansible.builtin.env', 'TF_VAR_spacelift_run_id') }}
              </a>
            </p>
          </div>
          </body>
          </html>
        mode: '0644'
