---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: catalog
resources:
- secret.yaml
- configmap.yaml
- service.yaml
- db-service.yaml
- deployment.yaml
- db-statefulset.yaml