apiVersion: ENC[AES256_GCM,data:b6w=,iv:h0cK6nh4/Yy5Z3xP+5PwwXGrT75t7e5ZN8uTwS1lIog=,tag:5pIimNyoO8ikGEMdWkEfBw==,type:str]
kind: ENC[AES256_GCM,data:DTWqpRg6,iv:1DsobqqgU7M9AI5hdpB727f+hsE5i2aD52T341yT+48=,tag:IQgy8Zi+ms6gAo4VdCpnTw==,type:str]
metadata:
    name: ENC[AES256_GCM,data:Cq/lG8sjpoYT8Q==,iv:bieMxNoeAoShQj3f1x51mhg7WlCGoutL39BOhMTevvA=,tag:4hdOyFGh5Hfjs2rvLLSKiA==,type:str]
data:
    username: ENC[AES256_GCM,data:AveUJcltFHgtrv2o98lsig==,iv:zsxhabPp5u1FH/mc7LukyasJac9OPapI2I8Rpc4Hwzk=,tag:EYQ2X3ps8OKbAgodGlVmeQ==,type:str]
    password: ENC[AES256_GCM,data:S+8ssVq0jberrNjNHCd1LZy7WWoeVdum,iv:psgy+4fvm0MyoocLfTM53IybJQFSIIFFgf+uRRpuw6s=,tag:0gCPcT5OH2jPn6X+A+aKGg==,type:str]
sops:
    kms:
        - arn: arn:aws:kms:us-east-1:234878555361:key/6462da8d-e99d-4bb6-98d6-1b7e8561ecc0
          created_at: "2026-05-09T01:06:45Z"
          enc: AQICAHgY705ep75advMMNqjqFAU9HqzlXqPTLCbJkjBlZDv5CAFJGlH2UvmoAe+26urqnjRdAAAAfjB8BgkqhkiG9w0BBwagbzBtAgEAMGgGCSqGSIb3DQEHATAeBglghkgBZQMEAS4wEQQMnUAs7TO+1gQZgavUAgEQgDvmRgsQYadGplS0gxlcdnW4TbUCSir7Gl7j1sLcbcEUkRCLtE+CP7vMSYQCaVHDSxbcUbX/0OV8Ewlcpw==
          aws_profile: ""
    lastmodified: "2026-05-09T01:06:46Z"
    mac: ENC[AES256_GCM,data:g4rJ7ipw1nLkFwBMB2mOtnIiROSazQKSY1Oqo6yPbQVsXbJOLqKyfL0dqF23zpLhNdNRpmio7ba+03mkGQCqAJN+bTlrqNWGiI5Wa4M9Nzd4Z69IYa/71e1wGuuj/cU/IKNvrCJvSsM50l/6EdUUpHWjgf8/HKmLzZz9813UZxI=,iv:C0tyridAV+BwzOaYV07myO/J+uPiMlupVvbA3E2286c=,tag:y8g4wMmQY1lB0/6BSO/Rlw==,type:str]
    unencrypted_suffix: _unencrypted
    version: 3.12.2
