---
apiVersion: ENC[AES256_GCM,data:9zw=,iv:Bh7VO6ZyJr6eI6rnWD8M6yYwpIDfRt9clV2lFVoxZqM=,tag:sPwcfaOkt+B94ehlfXypog==,type:str]
kind: ENC[AES256_GCM,data:eVPoT19A,iv:JPhd5Nuewc9tK+9ojg1k/ZJDKdlcXR90C0Gpkp5ssfU=,tag:r13kS7OfoERZPzsWDHCiUw==,type:str]
metadata:
    name: ENC[AES256_GCM,data:mW/DEgryTI0ozw==,iv:ELvJ80O5OPj13F6apHOfnoirA0gQkhMIRVz7eZSnq1g=,tag:hpEkawQtpinzOtZ2aM0YuQ==,type:str]
data:
    username: ENC[AES256_GCM,data:qB11GFl8aaPGgOifuygemA==,iv:Zgjy+F+8cX2Ut6x7LP5GSN2jAkGz6MGZU/1gPLCtyg0=,tag:Fgv5XqW+8mCFr6Xsd9v6hA==,type:str]
    password: ENC[AES256_GCM,data:iiFywArYtbrnNnYtvEo1A6WrJ0xiJxRy,iv:w4EM8FJcKA3OpRnR1dEm73d1iCfG8MeZB0z2+S9HcUQ=,tag:syBxZhnJfzS584FsONFcZA==,type:str]
sops:
    kms:
        - arn: arn:aws:kms:us-east-1:234878555361:key/54b96a99-ee11-4e46-93a7-7e3a130db583
          created_at: "2024-11-08T15:03:36Z"
          enc: AQICAHhWR/cL6re9GRvzeHMPbvB69g/BhSB9ZWifRozqB8kD1wF2V9QX/lkJxlMzDfkYX5s7AAAAfjB8BgkqhkiG9w0BBwagbzBtAgEAMGgGCSqGSIb3DQEHATAeBglghkgBZQMEAS4wEQQMvvo/LK2e/CQFZPNEAgEQgDusEy7HnngbYclXI1Voj6BcVEN5BRZmY9tfSuuHFZYvz0OQSfRa8pXXFIErBHFeeq4Uy2vroyNP+UxG9A==
          aws_profile: ""
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age: []
    lastmodified: "2024-11-08T15:03:36Z"
    mac: ENC[AES256_GCM,data:Qc+onhxKG7+C2yFRYDjYDNTj5sW/FOr2PVTRxsjm21yUG7Ij5mVuP5MYi0x+ju090slVs/idgor08sCh92EP74g3imGnnkSGYjlEOMbOmba6uOi4fjM/3Kpqs7cBia5aVXbOBVwHRVTBlAzOTrAKGP6bV/3npdaOoAznwLVinCc=,iv:Ji0LgkPu+UF3Eh+befFj1kuC9XLymqY3cYn7w4VqHJ8=,tag:NQ+An9eOU45ywTbBY141yA==,type:str]
    pgp: []
    unencrypted_suffix: _unencrypted
    version: 3.9.1
