apiVersion: ENC[AES256_GCM,data:/Oc=,iv:YkDlhxs4SBReBxUwrn5j0J957hvwIjmeAjTLpkp0mJ8=,tag:Chd94ppMPF3LLgUIhAmbDQ==,type:str]
kind: ENC[AES256_GCM,data:F86vrOJO,iv:LIs4ON+qEqKv1PA44tWk4INDijvKsjUFxMRIk2WnezY=,tag:cBLpNFNsFBcFiVaeYN/bhg==,type:str]
metadata:
    name: ENC[AES256_GCM,data:ynQa0YMaCmPnzA==,iv:CmLhw/JUGFHvjjUEYQ4sPhRqUVHFIwIYijDgcAPw9ek=,tag:xW5JCtnXmxl9eyHSID5eDw==,type:str]
data:
    username: ENC[AES256_GCM,data:N0acXRgXJy7rhMVi,iv:+jYMsH1CvwjRYqIiM0DPg2LHlqfx1krj/UJPUfyZVKY=,tag:QQujYZLOI/Wxb6iWLm+UkA==,type:str]
    password: ENC[AES256_GCM,data:zUGA3VdPNokTZ0DzN7Ctt0S7SigxkiK2RcmzqpHQxzU=,iv:hOppDPvqShT0lDPtf7ABrwD4HmH+pioNPBQgb29Axpw=,tag:rjXfnZXbyQNdQcew1ZqMLQ==,type:str]
sops:
    kms:
        - arn: arn:aws:kms:us-east-1:234878555361:key/cbaae98b-98fa-476f-9aa2-9e1aa8ded743
          aws_profile: ""
          created_at: "2026-09-11T14:59:54Z"
          enc: AQICAHg0pZ2PlnKDGczPYwDeMKqmciBBnd1RoVlVSGjhV7WbBwFQFDL1MszIeqFr2G6HxrUBAAAAfjB8BgkqhkiG9w0BBwagbzBtAgEAMGgGCSqGSIb3DQEHATAeBglghkgBZQMEAS4wEQQM5JvuNCv53s+s2oliAgEQgDsp/xpDd9aIQcPEHIfOJFFNSVGfYoo6IaacGQBQ+t0oIrRdcYi1SZTPZmY3ey1k4Huz6OPTaZSY815XyQ==
    lastmodified: "2026-09-11T14:59:54Z"
    mac: ENC[AES256_GCM,data:+FNyth/KYqR30HLFxLWihRPdKSQcD83kLORX/2VesvWBbg3SJkf5+D1ul1eoRd+QkzKoVU8evIZPrZTsexsnyNprX7B90DcS/5so+HaWdGhws0iZ7rL8+iwsNsS5IW9m4WfBo5TLlsYbmuRlU3UVDVNnMXdwscQZkGStffYbYDk=,iv:0hAr68RA8jurESUShf51P9cUvWcOSqS/2noVKq1vfeI=,tag:cCM3Id6EVZgi42jBkiVzYQ==,type:str]
    unencrypted_suffix: _unencrypted
    version: 3.13.3
