apiVersion: ENC[AES256_GCM,data:FXs=,iv:J6EmvA7WsU8U6xa91p4b/zKon8AvYP+gwV2VXDBqV3I=,tag:xzQPawJPr/3Vpfx0h9LcaQ==,type:str]
kind: ENC[AES256_GCM,data:g2BcWCQ6,iv:7aMxoz7KGBQ0k9yJqovZGRZ1fOXeVb1teIDIjmi/Sms=,tag:ywupyJmyNbTzB2EWBe/+jg==,type:str]
metadata:
    name: ENC[AES256_GCM,data:6uq1vQs8qQlVcHDsj5vxTJw=,iv:s1rWBZZ6B9A0F3/vk89Xtfo2btBagGXH9gc0HOYpqXs=,tag:HbnX1hmD6qL2porMLGOfnQ==,type:str]
    namespace: ENC[AES256_GCM,data:5RvlBCKmXr6O,iv:0Si9zbd9rS53ScjtsADXNsooWkaEbMnkgkzAyiyqgdU=,tag:bh8F8TY5hK7Y0Y99/9mhzg==,type:str]
type: ENC[AES256_GCM,data:XdJQvKbo,iv:8B8Mf6newjIOIlQjsWfYxB438O1eKlCXJBddzjxvvx0=,tag:Iohwk++WgyrBa3GlyWVZ6w==,type:str]
data:
    BACKEND_SECRET: ENC[AES256_GCM,data:+pKtGBT998ilMWja+gEGYCnKYj3q+fwrvyj7+qXhjH/VJTSV7J4f7kRdSNKN+9uGrWBiticlYk1np1ad,iv:OlFSg9QZeabcgH/N/a9IQ80qybyaGs1sGRl0G7vY6bg=,tag:nWGbTw+UW+v5SdXWtm9L4w==,type:str]
sops:
    kms:
        - arn: arn:aws:kms:us-east-1:234878555361:key/cbaae98b-98fa-476f-9aa2-9e1aa8ded743
          aws_profile: ""
          created_at: "2026-09-11T14:59:55Z"
          enc: AQICAHg0pZ2PlnKDGczPYwDeMKqmciBBnd1RoVlVSGjhV7WbBwHhXfiU71OPCGNsrXokcw43AAAAfjB8BgkqhkiG9w0BBwagbzBtAgEAMGgGCSqGSIb3DQEHATAeBglghkgBZQMEAS4wEQQMv0dmQi2xl1kMVb3EAgEQgDuAFyAEQVmCzys10qr68HRoCYlal1PP+H4BwNH36+R83c6vrJJsgBMsW7qqfTNb7x3+uxCkydB29aad7Q==
    lastmodified: "2026-09-11T14:59:55Z"
    mac: ENC[AES256_GCM,data:/e/AxwqmxoXM5oPH0sHuVQOzh6A3ECyXc+AZHwBAWKVcWS5Lh8aXl2KyPtZUPM7NHThpBjnvs65JoKWmUdbom2kOv5yzBi8UDgBkWsUxaDhy8tis6+1esl7EIY/sqRV2kV5eX4S0ZOY+CNQTY0u+4ZbcKRMznmV0Ssk/09UXmeg=,iv:u5gpxVG08E2U1N6LpuEVEPu//PNkl9JzCc7u5g/9jfo=,tag:4gdCUlWnIo55HgG97ZNDCg==,type:str]
    unencrypted_suffix: _unencrypted
    version: 3.13.3
