apiVersion: ENC[AES256_GCM,data:Uak=,iv:Tpj5upxnnZFMevJgK06IWGs1VdXuBXIJnrKx0LBAdNs=,tag:ZQJYIyCc7tqjQT4DqJsa6Q==,type:str]
data:
    BACKEND_SECRET: ENC[AES256_GCM,data:5nuJqKQSir96XAn/lvOrUhMQHIAjTfdFlLKRepqmxxGeaviG26wdAb4tud7X/ECHptOPD+GLBLEbVwma,iv:erC8/tZOyeS2P3WnpENapP6J2WH4OLhk3rMjFkY5iuE=,tag:fSnyGZUwchXP0meVNvlTPw==,type:str]
kind: ENC[AES256_GCM,data:hcJxsbou,iv:NxiocubABtn16vDrhUwF3FW78HXgutRa2u0v0M7t3wY=,tag:TK4udYS3SaVwoTgfaWiYOA==,type:str]
metadata:
    name: ENC[AES256_GCM,data:Mrv3KgAAxFSWe7V9RbpS6Bk=,iv:isLIvlMym2ltx/VrmKEvOHSBx+2OKmfHls+d8ctfWtI=,tag:6uXIpWOMset0PWc+q/1ZFg==,type:str]
    namespace: ENC[AES256_GCM,data:g0/AEjX/Ffrb,iv:RdK2LtX1mdPwia3J9WKBYK/GmJq45YA5HtSUJi9jsxo=,tag:z4PSuZPRAVKWXwSwsIovjQ==,type:str]
type: ENC[AES256_GCM,data:7IbvM264,iv:VIH3L+VKnh902eGri+YnB2ziqYQ7RjsoZXO7NEvg21Q=,tag:8BzFkzp/39vGH1/MmPM4MQ==,type:str]
sops:
    kms:
        - arn: arn:aws:kms:us-east-1:234878555361:key/6462da8d-e99d-4bb6-98d6-1b7e8561ecc0
          aws_profile: ""
          created_at: "2026-05-09T01:02:10Z"
          enc: AQICAHgY705ep75advMMNqjqFAU9HqzlXqPTLCbJkjBlZDv5CAH+UO+ba/f8YjWWN2zaDxncAAAAfjB8BgkqhkiG9w0BBwagbzBtAgEAMGgGCSqGSIb3DQEHATAeBglghkgBZQMEAS4wEQQM8OHy1h0bceI77aPfAgEQgDsSUOJxKijuS7TQeBrX+6nsxZ7TpUr36CP5cRunZGi1weBJltk9KukBHfGy7WGOnFuZzDPoZdB7SMTP4g==
    lastmodified: "2026-05-09T01:02:10Z"
    mac: ENC[AES256_GCM,data:fD/ce6kQup/rCGA9YzTPGzTzYiXMKKQMYYGWkPoxqgkclPilOI/y7S1Z0VZ2SZEUr6dza2w6iOaS4hXxJRPyQwcgAaTJT7RHHAwZd6XXFGoCegk+EzFN80wd/se9HeCDXAIvxj/o/Wc9R6YMuhEWULwwuwPnMAZ7xHaWG/l92p0=,iv:Vzz0WCWN+TfR3eKmSRE0gno0qLskPgSmoXT8t0RDwGw=,tag:ot4a2TYAj5bi6vCQp42FOA==,type:str]
    unencrypted_suffix: _unencrypted
    version: 3.13.0
