apiVersion: ENC[AES256_GCM,data:io4=,iv:YlLGKw48QhXtqRENl4ZEOeODJZAdYdHvYYb20L44uUI=,tag:at6km0AvvQ2SQgypWD02jQ==,type:str]
kind: ENC[AES256_GCM,data:doow9JCU,iv:2BryzDReotqpd3kSHYUdmbLFPDooKdNWEn01fXtpXDc=,tag:MzYoYfCKAu4OtAnIvpAf4w==,type:str]
metadata:
    name: ENC[AES256_GCM,data:iW26SzMnjxh7/odTT5GnIg==,iv:hJuxyAdiL/K9wPh78rOGeHWbMvWQJ+Ej7fJi+17Tgeo=,tag:Fu813MUDaXiOEUW01qusFg==,type:str]
    namespace: ENC[AES256_GCM,data:PxPHas/KHxFP,iv:8CG/hI/bRi0J8C2fpaeGiWLst3HmCnMavWR9HC1Knos=,tag:7LPyyVjWnWqvaSWebx5cQw==,type:str]
type: ENC[AES256_GCM,data:GpRCDju1,iv:x0dltFcRwOOIDynz8kZZ8NW1O72zzMa8eVUQRtsgM4A=,tag:oOgmIy+iWJBgCy0HV83wdA==,type:str]
data:
    POSTGRES_HOST: ENC[AES256_GCM,data:KGHpiDtPAXOj+e3whiq4xMzuFCBA3YYL,iv:aMInrTlZWFZwpauGMuiAMnejvG1iKu/VWf+BI5URnsg=,tag:ZQy4S3Z6+S9C7BogLHDuaw==,type:str]
    POSTGRES_PORT: ENC[AES256_GCM,data:MOXGTwLTEyw=,iv:RqQU0fSgxWaFxhSi3wROygdJWpTOqgJlb5envp/4Kio=,tag:ElYR4dQQ9i+8lxw5MQ0zjQ==,type:str]
    POSTGRES_USER: ENC[AES256_GCM,data:4vPAeJkEkT+F7Slo,iv:Kmjhm3vpXa20G738ggJv/FSZ15khRNS+7n2q+o+b1II=,tag:QauKUUn4KJdbS0t14Ew6Ow==,type:str]
    POSTGRES_PASSWORD: ENC[AES256_GCM,data:xwzY6pbsxfteRdsMjsjNvSga20hyRm3GoLIciyeg0qk=,iv:PPqcGW3ho79FQvr7o69j3C5Pxo9r3510vKzyhPzuKQc=,tag:4T+Z1d+mgGrCZXC++QEzAw==,type:str]
sops:
    kms:
        - arn: arn:aws:kms:us-east-1:234878555361:key/cbaae98b-98fa-476f-9aa2-9e1aa8ded743
          aws_profile: ""
          created_at: "2026-09-11T14:59:55Z"
          enc: AQICAHg0pZ2PlnKDGczPYwDeMKqmciBBnd1RoVlVSGjhV7WbBwGi7TSVZtayyFF7+nZU3FNCAAAAfjB8BgkqhkiG9w0BBwagbzBtAgEAMGgGCSqGSIb3DQEHATAeBglghkgBZQMEAS4wEQQMoPP4b/wCJP46wg9TAgEQgDureIo1oo1kYvb67wuwKTlykh2BEHSyNPjX9ew026dG0XR9PfzPNnTqZTJ0qw+/laa6wRXYpNIp0C37fA==
    lastmodified: "2026-09-11T14:59:55Z"
    mac: ENC[AES256_GCM,data:vqOMXgavoP1oRANYnWDV4C67Xl1iERsi6Nq3+c5nDRvBBR0WGrkjWNFtMIuE76IAIU3uIWKyO0BEbtmJS+qajLrQqwMCL1zvgjEJ+aTFLlzEa6TyTQwj3obcJOO0GU4AEflSsly7PqzfS7fgvY1+G7h8PdhhGFG30DSwJf8upSE=,iv:YyBaRNNz4K3hXaDzQSNuQd9tClEzYiYJ70Q4+6BCbuI=,tag:DfbgBfCxpHV8UDxSwz+XgA==,type:str]
    unencrypted_suffix: _unencrypted
    version: 3.13.3
