apiVersion: v1
kind: Service
metadata:
  name: backstage
  namespace: backstage
spec:
  internalTrafficPolicy: Cluster
  ports:
    - name: http
      port: 80
      protocol: TCP
      targetPort: http
  selector:
    app: backstage
  sessionAffinity: None
  type: ClusterIP
