---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: orders
resources:
- namespace.yaml
- secret.yaml
- configmap.yaml
- serviceaccount.yaml
- service.yaml
- mysql-service.yaml
- deployment.yaml
- mysql.yaml