apiVersion: ENC[AES256_GCM,data:OhBxsMhg1g==,iv:PKA0PdxVGsYL8mc/TUlhXlEzQJybsSE//bmn5mUz8lE=,tag:A0wNr0m13MZC0COOteZHaw==,type:str]
kind: ENC[AES256_GCM,data:SaARKREoQFW1rw==,iv:+vg1slFqp92fg6PXzoWAu+rr7RNdzmWKg3s7RUnoN7o=,tag:u8AmbZR3PX5QyeMUmccgVg==,type:str]
metadata:
    name: ENC[AES256_GCM,data:L98bGNmOU9wvt0bF,iv:rUeNPO8Fmsip5IqWFKuL3Xmy0Ju8Jfx7zgLGQi8h6wQ=,tag:oPLyNa5U+ExQexLAG8/5Jw==,type:str]
    labels:
        app.kubernetes.io/name: ENC[AES256_GCM,data:ZWhQTl0I,iv:t29DwbaVMLSbmav58LxDtiA87IWZjjxeiKMQc4Jw7Us=,tag:c+mResPkdkLSy31nLGJmqg==,type:str]
        app.kubernetes.io/team: ENC[AES256_GCM,data:uibM0S3K,iv:g3bqki4TEERT/nc1lU3oDsrHgPkYvp+bfhGI/pIqFEE=,tag:rBCbqI9Ev9jcb31JjR12TQ==,type:str]
spec:
    replicas: ENC[AES256_GCM,data:aw==,iv:CQPJQPQQFzQFDoSCZvvHHRYwaiWQqVsbdMC1SLN+8GU=,tag:rdVf+lTprg0o9P478fcB9A==,type:int]
    selector:
        matchLabels:
            app.kubernetes.io/name: ENC[AES256_GCM,data:FPSwrlaH,iv:+N8XQfJL70j4uTIM8FHZfRGAgLNXhYFPCWvhx2uYumg=,tag:A32DHzmZtmF46tXvxZJFLw==,type:str]
            app.kubernetes.io/instance: ENC[AES256_GCM,data:W8AHBxnB,iv:41/c3ApBj/zsF15vhz1wCE1a/qY/BHBqgbsUQfOPQ2c=,tag:/ZXhTRiltC0JwQH2f9IQww==,type:str]
            app.kubernetes.io/component: ENC[AES256_GCM,data:z0Axgvw=,iv:rmWI+0Zxt8JHH/TXp/Bz5Q2ecWQRzZfGiUFSUqQQRcQ=,tag:0oJsfSoWQiMwASqRHXXmBQ==,type:str]
    template:
        metadata:
            labels:
                app.kubernetes.io/name: ENC[AES256_GCM,data:aeC+hqIQ,iv:zTw3wDaifisgl5+ITZzc9xhmElygNqCZYvmvCzaiB1U=,tag:hFuel1PdGSxqczy6gsH6Vg==,type:str]
                app.kubernetes.io/instance: ENC[AES256_GCM,data:JO2PJ4CJ,iv:a4vNT22XsxGFzWiW4T9g3/yw0//QC1HRuI5WFdS4x8c=,tag:9emHxYajj4ex0J3tPM4BwA==,type:str]
                app.kubernetes.io/component: ENC[AES256_GCM,data:hCz/A/A=,iv:NWkylOgArLSboLennGFEy/HalRocEdDknnvmlwZoqtk=,tag:15l/3q1lQci2U8JvcBQAig==,type:str]
                app.kubernetes.io/team: ENC[AES256_GCM,data:/bh/68h8,iv:4vgBlHOiw28DJ77+UewpdvRAgWkyMlE29cSDgfmn1iY=,tag:PEg8hnuzjANvA8YfqEMEyg==,type:str]
        spec:
            containers:
                - name: ENC[AES256_GCM,data:WoHhDKo=,iv:XNFSGSBeS/guwek6nGRYovjRXYeJ8oC5YQtjnXqaGkw=,tag:Czm5vP9IOEge0we2ChnHbA==,type:str]
                  image: ENC[AES256_GCM,data:C8oU9YQl6Dd+WeoNMs5bc4wTJtV/CTQ4ppyK3ediR1C7gxfxR1Bh,iv:hrJzCk9P15IT1xkrawhkf9ybTMawm/Joa068qTRee2s=,tag:+bDZ8oI/OsEvmtniTFesLw==,type:str]
                  imagePullPolicy: ENC[AES256_GCM,data:/Ciir+yCyPakiZFc,iv:0QqCoRW3mX4TFQivCBkqkEdejAAUI24D89ct5Wxx5r8=,tag:vJkmJEQrDFtmZAZBHycxWg==,type:str]
                  env:
                    - name: ENC[AES256_GCM,data:yIjvG5s63K0w7ZY/EaXDu+ZhHg==,iv:N0dodJqIjJKokl1uGgFQifkwnEPO/FlYJzCjSwiKn5I=,tag:DvriaZkQjM6i3rhBNWarbw==,type:str]
                      value: ENC[AES256_GCM,data:iphAIaNS6iaSRIAZ/gJjIm4sLqcwZQ6m,iv:eUalGFttQ39UPcezIWNU9NNcW2muj8SDzYYjroa46/M=,tag:px4EJiuwEgSWcosxYd0okw==,type:str]
                    - name: ENC[AES256_GCM,data:ZJeNA/l4nddhKPGzDdg=,iv:AVX/y2CNY/hJECZ9HQTdwUurP0j+RtGejji6WCSzTj0=,tag:Si6qAVoHxeDRlu5SikWHeg==,type:str]
                      value: ENC[AES256_GCM,data:3/5bP4zz,iv:d/Zfpi/MmrmgAWRcc4beLaNm6+SDR27oSh9k4FCtKjo=,tag:NM1260YkltjTSpOmbhx22w==,type:str]
                    - name: ENC[AES256_GCM,data:xq262fz/HK62yg==,iv:rsmbTZ70kWQtVqKKS0xwzN/cJKEQhGi4AbxVfHocxj8=,tag:4MoZDUJwKYU+xDe9GU4Vfg==,type:str]
                      value: ENC[AES256_GCM,data:FAm6eAoL,iv:kFwcU7xqPTeuCDIQGCQuuRDJOhHO7f1di8/S69Trcis=,tag:AMdQfpd/6J+8oCEwxtMkzA==,type:str]
                    - name: ENC[AES256_GCM,data:96ZnIAITPo1DcQoTj2Y=,iv:xjYWloP50InVQ9kN1glgp2mFjRbIYJPQ6HHs6jbeJI0=,tag:tjfZ3Yuffh7PuIstp3mYYQ==,type:str]
                      value: ENC[AES256_GCM,data:Ozxd8nNppfOQJRa1uptHrZYddg/ucYcn,iv:LSLVgi2vFO3wcPkeltQrMX38xrOBV9xohbnJIk5wXm4=,tag:bb/5ZsowgoTRZKLNppNbGg==,type:str]
                  ports:
                    - name: ENC[AES256_GCM,data:a2jKZ38=,iv:Chb8p5u0PQGNBMuHZt4BWSDGLq1EHyN7PPT7o3gUyyM=,tag:kN26VU7Lhm2PaYmG9gZtyg==,type:str]
                      containerPort: ENC[AES256_GCM,data:rq77Iw==,iv:Dwnf0THoWKiGn/nwFJEnmsHjnvuVx+mlm4pdFMG/Z3k=,tag:emFMPnclSzBtfmun1bFM3Q==,type:int]
                      protocol: ENC[AES256_GCM,data:DHQC,iv:E/cGJdOhrudunbBn0OZItFzyJGWxvXmUKhOZC+mlFXo=,tag:E6U4Z5l2WIw0t3QRKOmaaA==,type:str]
sops:
    kms:
        - arn: arn:aws:kms:us-east-1:234878555361:key/cbaae98b-98fa-476f-9aa2-9e1aa8ded743
          aws_profile: ""
          created_at: "2026-09-11T14:59:54Z"
          enc: AQICAHg0pZ2PlnKDGczPYwDeMKqmciBBnd1RoVlVSGjhV7WbBwEfztt9UmaiBUGM6tHdze71AAAAfjB8BgkqhkiG9w0BBwagbzBtAgEAMGgGCSqGSIb3DQEHATAeBglghkgBZQMEAS4wEQQM7tlsRgjmjv11lyrIAgEQgDv2fbPLp3s7GW+oH+ywpx9cCerhufQ5bblT0q6w9gFWacPgRXQaB861RCcJyUhQZvL89JxnpsVY/OK7Mg==
    lastmodified: "2026-09-11T14:59:54Z"
    mac: ENC[AES256_GCM,data:dcJ/bCmUBmdz2QtZu5i7NtBASCiTuytbuYToO0z6s/zj3/ICInBsYwfrcB277LxhCPu5FtwFJRSjGl/h902ZlP3v/67oAPN2VoZ4dEegf98AwcjOsgfS+xNdvhClllyWaC65vKhCkmK5KlHE20a59IGKk2kDs7WEXrhIPsf9Q74=,iv:YwT4NeJ0WoEXBaysDgzt1/b1DbOe9DOyIBao7TY51Gs=,tag:InQ16efIQECrEWj+IZ2JMQ==,type:str]
    unencrypted_suffix: _unencrypted
    version: 3.13.3
