apiVersion: ENC[AES256_GCM,data:cCw=,iv:D7zMFwzZe2aUaMP8kSsMK4pXFk45T3HPDKfR4+vJcFw=,tag:1vz2jRht0oLPBaSUkz58mg==,type:str]
kind: ENC[AES256_GCM,data:OxU+oOjl,iv:elwp7zVqnxFPtS4Zr3Wlw+0ADd+MeWUIja7hP7fskK4=,tag:R2aaFJrxoZuna0g0c06oow==,type:str]
metadata:
    name: ENC[AES256_GCM,data:dSh0xZfzpnSb,iv:Fe1awNWkSkS+4tfBL0QSJPx/LF2F01eDfTsUkVmX234=,tag:hmN5oA7gMIWkbw2A78snKA==,type:str]
data:
    url: ENC[AES256_GCM,data:7YnyLoJ+7gkn2lkckZ9UuA7EX+uiqB9Plth4T7DoYyhtDymN1zML+P9OgbUAGcwqZ8oaSA==,iv:5H9JWYuNzbmRL2Erzz7adDTkQRBrh7AVg6+IzyV722U=,tag:z7OKgVO3UwajQUS5MpPQcw==,type:str]
    username: ENC[AES256_GCM,data:VfYoCGKb9QXufNlI7zWnfw==,iv:+iZpIi7PBsAihL4o5XZj7kZ8LVP+HWMvXQrBdl/SmJU=,tag:m5Ki0uLqLbJAfMLg2wvw4Q==,type:str]
    password: ENC[AES256_GCM,data:8XUG1d4vzNXJVSWbAihfFVaFWy+IIpu9,iv:kHHaO0XG6JZLDLAk3NXefKrZeDOYWXlDXCvOEvclgeg=,tag:0F2PtVROIbH/zcf+4FgQwg==,type:str]
sops:
    kms:
        - arn: arn:aws:kms:us-east-1:234878555361:key/6462da8d-e99d-4bb6-98d6-1b7e8561ecc0
          created_at: "2026-05-09T01:06:45Z"
          enc: AQICAHgY705ep75advMMNqjqFAU9HqzlXqPTLCbJkjBlZDv5CAGe4nucZ/LVD629esu/mbaQAAAAfjB8BgkqhkiG9w0BBwagbzBtAgEAMGgGCSqGSIb3DQEHATAeBglghkgBZQMEAS4wEQQMI78Jn19pC/A/7NSzAgEQgDu+I1smUDsgVCzcPrioPJB/iKC54NNnzgt+so3QMZrSzorW1AlDP/3tECF3Cx1AeWYus/Box2PzCDNbzw==
          aws_profile: ""
    lastmodified: "2026-05-09T01:06:46Z"
    mac: ENC[AES256_GCM,data:DSBnVA0184LHlY9Qtszs64non6P6KEB9EPh4P016VdNXZZXgSwlJYuDJLZg/w3n5TYxlo/YRqy238R/N3ps9+8ezzCRuWXm79C1/ZZ9Qz1Q2iXWQ1gJQI/jZRCkj7dhtmKRUHTzGqZi23raK39cVWMyVa87K3lIbjNuXVgtmuaQ=,iv:gCoUuRaw0zMKb5IxTf/zKeAWrfD6+oNPGgoODBQ2pwo=,tag:SIY1fpNCjuOf1SulDs+jTg==,type:str]
    unencrypted_suffix: _unencrypted
    version: 3.12.2
