apiVersion: ENC[AES256_GCM,data:Xfo=,iv:pySK1JO6VcTcNWYEu6xgbLDXxAOBW0sd1pHA8KYAQcQ=,tag:LHGku10gkCtim9neaJGXmQ==,type:str]
kind: ENC[AES256_GCM,data:LSkfvB6c,iv:elllfJ8MsviovtEGzkbXaqC/A05gPKTv9E3Nw5/gMWY=,tag:Eg2aJQQyCnLTs8BRuUS3TQ==,type:str]
metadata:
    name: ENC[AES256_GCM,data:pDLm2dbV/tC3,iv:UX83pPYAp2r3TiGz+VuHCDOeMKTtKkyOZ8/sW3pduVY=,tag:dYu1G6OzfPVS9Duh58T5WA==,type:str]
data:
    url: ENC[AES256_GCM,data:1FPRyCUJLu4g4/jxjr8terBrOYhZqXfJqTrjFj2eV6/LhuzT6mcMIBMG+rzymSCc6GKK6g==,iv:N5tCYuKWsXv9i2BMUsLhqR3KsP1Gl83Usm0zcra6uws=,tag:e7CZpwNdhcKctT6ms21cDA==,type:str]
    username: ENC[AES256_GCM,data:KtYyPTqPwoc=,iv:TYA+XDx6XxcA1ZoMG1l0Eol0PEVPjRFS0laFJ81BmWs=,tag:82X+dPsZbSi3h9bR5jY2sQ==,type:str]
    password: ENC[AES256_GCM,data:fW1O6dgeJsYMsI/Y5LSA6qvLlVylZJ08mOU5Uo0NDOI=,iv:fTC6bFjEva4xRVXdIJKjKBCtMYmHRPnXlTBCVSU5FbI=,tag:pFUVez3ftaJgQJoiuRuKwQ==,type:str]
sops:
    kms:
        - arn: arn:aws:kms:us-east-1:234878555361:key/cbaae98b-98fa-476f-9aa2-9e1aa8ded743
          aws_profile: ""
          created_at: "2026-09-11T14:59:54Z"
          enc: AQICAHg0pZ2PlnKDGczPYwDeMKqmciBBnd1RoVlVSGjhV7WbBwHD4XB5ikjADx/ZtzWx1cTFAAAAfjB8BgkqhkiG9w0BBwagbzBtAgEAMGgGCSqGSIb3DQEHATAeBglghkgBZQMEAS4wEQQM9M6B5z6G1rVDbfPtAgEQgDsv+p+J0XpucKbfbv9MiYgEq1wBzxejPQ3lic9rdUNByA9ZOupGm7L9rs6pF1BiA6IxdKY3S1E8qYzCdw==
    lastmodified: "2026-09-11T14:59:54Z"
    mac: ENC[AES256_GCM,data:2iTf7xNsg57QtgzM4zrnv3jh57bgtutgaoLLvpdJZoCeDZCCJ59yO2IC1+6fhKCzk97O2IwbebJsI7G49nWZUxNspIhP+W08mJb9RwYJ4SOwa3aJQkJE4rVNhc8Gp3Pj96bS7oDUXcQjXvCG08cTc7tQnd8nfw9mujxU0MIOqco=,iv:5RnSagmUJlqXb45Lt/bzdnjXPLWz1wrSwmDhcDgzxLM=,tag:+FrmjoOX+f86aHYTCxG6BA==,type:str]
    unencrypted_suffix: _unencrypted
    version: 3.13.3
