apiVersion: ENC[AES256_GCM,data:5zk=,iv:IC6UXBLojZYWL5zNlk7FT25VYWkBOYbEdSjJMMoRrPM=,tag:dot6p0BZzPZtzmuhKHDGsg==,type:str]
kind: ENC[AES256_GCM,data:DowquwN3,iv:3y507G4fp3nWYgNKJhou49meKlkcW4yMiAYwwDRndgU=,tag:KM7isNgEY+Ae7sRopeF4Ng==,type:str]
metadata:
    name: ENC[AES256_GCM,data:l2ffCzyQPSGF,iv:o3EGB6rEonCskPsncQO8/F73xyhfBHkDE0oCnImvXGY=,tag:QAW38hIN66ieWKA1hw/IlQ==,type:str]
data:
    url: ENC[AES256_GCM,data:zJmPVxJoQM9gCR8gd4QTl5w/jtog0ykUGdzla+hLK0Jebb9uUnCLnz40xTipiuiVp9VPJw==,iv:hr7rcrgLPg6daU6+OqooCfwACoaXJdgUWpE8sGZnoj8=,tag:MXUFwi5bB5aIu9DO7D8hMg==,type:str]
    username: ENC[AES256_GCM,data:1ZMGAFLmaS1QHu2Iq4XevQ==,iv:FURasZtz8lUb6Yipl50B7s5Xe2lt1tQemjuzlLOZq30=,tag:Tv+onFWs0DH/MTxQ8gBhMw==,type:str]
    password: ENC[AES256_GCM,data:DumSM8/xXmuBdVtF/sYYNrCv6NAOryx8,iv:6XcsrPBy8D02Q91M1oFINi57QpZxx7VmKdmx13wCDWE=,tag:1ptNW8RdTiDZtSM9ZxVYJQ==,type:str]
sops:
    kms:
        - arn: arn:aws:kms:us-east-1:234878555361:key/54b96a99-ee11-4e46-93a7-7e3a130db583
          created_at: "2024-11-08T15:04:00Z"
          enc: AQICAHhWR/cL6re9GRvzeHMPbvB69g/BhSB9ZWifRozqB8kD1wG+sCOmRx7b1Jd7k32ZlUodAAAAfjB8BgkqhkiG9w0BBwagbzBtAgEAMGgGCSqGSIb3DQEHATAeBglghkgBZQMEAS4wEQQMeQZPzMgx2KYqUAqiAgEQgDuDy+yauDgpGMXaucDuiCyW5uWoIf5fqiEzfDik6cSpI50vdMzK/l2vgYJyIbi79WI03QGWqKy64LGSXw==
          aws_profile: ""
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age: []
    lastmodified: "2024-11-08T15:04:00Z"
    mac: ENC[AES256_GCM,data:KdIT0MTY3V/wGNW2wNxJtkHNpQ10Z5TxcJcxDFZ8GPEWbmaZCUvSPIIKbStR2+TU0lcw0XoixqroEuQcMPVUeksIYO5ZcF8ptsSFmCm6lrl7QuZ+Ry02NWQLns/J8PeQDsl72Kb/qOni19MEcs+jI5GnLz8xlqxEHZuONJg00b0=,iv:RWXfHvPRTHK+Juo8YiwiWWbdbcoTbodxuFSlgJW1S68=,tag:hHbiuntE2VBc8ZEMVoNz9g==,type:str]
    pgp: []
    unencrypted_suffix: _unencrypted
    version: 3.9.1
